name: ROS test workflow

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic

        #- name: setup catkin tools
        #run: |
        #sudo apt update -qq
        #sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\" > /etc/apt/sources.list.d/ros-latest.list"
        #sudo apt-get update
        #sudo apt-get install python3-catkin-tools

    - name: Init workspace
      run: |
        source /opt/ros/melodic/setup.bash
        mkdir -p ${CATKIN_WS}/src && cd ${CATKIN_WS}
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/
        catkin_make

        #- name: Run tests
        #  run: |
        #source ${CATKIN_WS}/devel/setup.bash
        #rostest <package> <node.test>
